# Generated by Django 2.2.10 on 2020-05-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='price',
            field=models.IntegerField(),
        ),
    ]
